/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 28-abr.-2023 5:56:25 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS Cuenta CASCADE
;

DROP TABLE IF EXISTS Cuenta_ProductoServicio CASCADE
;

DROP TABLE IF EXISTS Habitacion CASCADE
;

DROP TABLE IF EXISTS Hotel CASCADE
;

DROP TABLE IF EXISTS Huesped CASCADE
;

DROP TABLE IF EXISTS Pago CASCADE
;

DROP TABLE IF EXISTS Persona CASCADE
;

DROP TABLE IF EXISTS ProductoServicio CASCADE
;

DROP TABLE IF EXISTS Registro CASCADE
;

DROP TABLE IF EXISTS Reserva CASCADE
;

DROP TABLE IF EXISTS Tipo CASCADE
;

/* Create Tables */

CREATE TABLE Cuenta
(
	k_numeroCuenta serial NOT NULL,	-- Es el numero con el que se identifica cada cuenta
	i_estado varchar(9) NOT NULL,	-- Este permite saber si el valor del consumo asociado a la cuenta está pago o no
	v_valorConsumo integer NULL,	-- Este es la suma de todos los productos o servicios que se consumieron en el hotel 
	k_reserva serial NOT NULL	-- Es el numero que identifica cada reserva
)
;

CREATE TABLE Cuenta_ProductoServicio
(
	q_cantidad smallint NOT NULL,	-- esta es el numero de veces que uso o consumio un servicio o un producto
	f_consumo date NOT NULL,	-- Es la fecha donde el huesped hizp el consumo
	k_numeroCuenta serial NOT NULL,	-- Es el numero con el que se identifica cada cuenta
	k_producto integer NOT NULL	-- Es el numero con el que se identifica cada producto 
)
;

CREATE TABLE Habitacion
(
	k_numeroHabitacion smallint NOT NULL,	-- Este es el numero para identificar cada una de las habitaciones
	k_tipo char(1) NOT NULL,	-- Es el tipo de habitacion que se puede elegir (Simple, Doble, Triple)
	k_hotel smallint NOT NULL	-- Es el identificador del hotel
)
;

CREATE TABLE Hotel
(
	k_hotel smallint NOT NULL,	-- Es el identificador del hotel
	q_diasDescuento smallint NOT NULL,	-- Es el numero de dias que se establece para aplicar por el descuento
	t_descuento smallint NOT NULL,	-- Es la tasa de descuento que aplica luego de hospedarse esos n dias 
	t_aforo integer NOT NULL,	-- Es el numero maximo de personas que pueden estar dentro del hotel
	q_capacidad integer NOT NULL	-- Capacidad máxima del hotel
)
;

CREATE TABLE Huesped
(
	o_direccion varchar(50) NOT NULL,	-- Esta es la direccion de residencia del huesped
	o_telefono integer NOT NULL,	-- Este es el numero telefonico personal del huesped
	f_nacimiento date NOT NULL,	-- Fecha de nacimiento del huesped
	k_tipoDocumento varchar(3) NOT NULL,	-- Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"
	k_numeroDocumento bigint NOT NULL	-- Este el el numero de identificacion unico de la persona
)
;

CREATE TABLE Pago
(
	k_pago integer NOT NULL,	-- Este es el numero unico asociado a cada pago
	f_pago date NOT NULL,	-- Fecha en la que se hizo el pago
	n_formapago varchar(50) NOT NULL,	-- Es la forma que elige el huesped para hacer el pago
	v_totalPagado integer NULL,	-- Es el total a pagar
	k_numeroCuenta serial NOT NULL	-- Es el numero con el que se identifica cada cuenta
)
;

CREATE TABLE Persona
(
	k_tipoDocumento varchar(3) NOT NULL,	-- Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"
	k_numeroDocumento bigint NOT NULL,	-- Este el el numero de identificacion unico de la persona
	n_primerNombre varchar(20) NOT NULL,	-- El primer nombre de la persona
	n_segundoNombre varchar(20) NULL,	-- El segundo nombre de la persona (Opcional)
	n_primerApellido varchar(20) NOT NULL,	-- primer apellido de la persona
	n_segundoApellido varchar(20) NULL	-- segundo apellido de la persona (opcional)
)
;

CREATE TABLE ProductoServicio
(
	k_producto integer NOT NULL,	-- Es el numero con el que se identifica cada producto 
	n_producto varchar(50) NOT NULL,	-- Es el nombre de cada producto
	v_precioUnitario integer NOT NULL,	-- El valor por unidad de cada producto
	i_tipo char(1) NOT NULL	-- Permite saber si es un producto o un servicio lo que consumió el huésped
)
;

CREATE TABLE Registro
(
	k_numeroRegistro serial NOT NULL,	-- Es el numero para identificar cada registro
	f_entrada date NOT NULL,	-- Fecha del check-in en el hotel
	f_salida date NULL,	-- fecha del check-out del hotel
	k_tipoDocumento varchar(3) NOT NULL,	-- Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"
	k_numeroDocumento bigint NOT NULL,	-- Este el el numero de identificacion unico de la persona
	k_reserva serial NOT NULL	-- Es el numero que identifica cada reserva
)
;

CREATE TABLE Reserva
(
	k_reserva serial NOT NULL,	-- Es el numero que identifica cada reserva
	f_inicio date NOT NULL,	-- Es la fecha desde que la persona estaria hospedada en el hotel
	f_fin date NOT NULL,	-- Es la fecha en la que terminaria la reserva en el hotel
	f_reserva timestamp without time zone NOT NULL,	-- Es la fecha exacta en la que se hace la reserva
	q_nochesReservadas smallint NOT NULL,	-- Es el numero de noches que la persona reserva
	q_numeroPersonas smallint NOT NULL,	-- Es el numero de personas que estarian incluidas dentro de la reserva
	v_precioEstadia integer NOT NULL,	-- Es el precio total de la estadia en el hotel
	i_estado varchar(9) NOT NULL,	-- Este atributo permite conocer si la reserva ya esta paga, no paga o cancelada
	k_numeroHabitacion smallint NOT NULL,	-- Este es el numero para identificar cada una de las habitaciones
	k_tipoDocumento varchar(3) NOT NULL,	-- Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"
	k_numeroDocumento bigint NOT NULL	-- Este el el numero de identificacion unico de la persona
)
;

CREATE TABLE Tipo
(
	k_tipo char(1) NOT NULL,	-- Es el tipo de habitacion que se puede elegir (Simple, Doble, Triple)
	v_precioNoche integer NOT NULL	-- Es el valor que se le da por noche a cada habitacion, dependiendo el tipo que elija
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Cuenta ADD CONSTRAINT PK_Cuenta
	PRIMARY KEY (k_numeroCuenta)
;

ALTER TABLE Cuenta ADD CONSTRAINT CK_k_numeroCuenta CHECK (k_numeroCuenta > 0)
;

ALTER TABLE Cuenta ADD CONSTRAINT CK_i_estado CHECK (i_estado in ('pendiente','paga'))
;

ALTER TABLE Cuenta ADD CONSTRAINT CK_v_valorConsumo CHECK (v_valorConsumo >= 0)
;

ALTER TABLE Cuenta ADD CONSTRAINT CK_k_reserva CHECK (k_reserva > 0)
;

ALTER TABLE Cuenta_ProductoServicio ADD CONSTRAINT PK_Cuenta_ProductoServicio
	PRIMARY KEY (k_numeroCuenta,k_producto)
;

ALTER TABLE Cuenta_ProductoServicio ADD CONSTRAINT CK_q_cantidad CHECK (q_cantidad > 0)
;

ALTER TABLE Cuenta_ProductoServicio ADD CONSTRAINT CK_k_numeroCuenta CHECK (k_numeroCuenta > 0)
;

ALTER TABLE Cuenta_ProductoServicio ADD CONSTRAINT CK_k_producto CHECK (k_producto > 0)
;

ALTER TABLE Habitacion ADD CONSTRAINT PK_Habitacion
	PRIMARY KEY (k_numeroHabitacion)
;

ALTER TABLE Habitacion ADD CONSTRAINT CK_k_numeroHabitacion CHECK (k_numeroHabitacion > 0
)
;

ALTER TABLE Habitacion ADD CONSTRAINT CK_k_tipo CHECK (k_tipo in ('S','D','T'))
;

ALTER TABLE Habitacion ADD CONSTRAINT CK_k_hotel CHECK (k_hotel > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT PK_Hotel
	PRIMARY KEY (k_hotel)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_t_aforo CHECK (t_aforo > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_t_descuento CHECK (t_descuento > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_q_diasDescuento CHECK (q_diasDescuento > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_k_hotel CHECK (k_hotel > 0)
;

ALTER TABLE Hotel ADD CONSTRAINT CK_q_capacidad CHECK (q_capacidad > 0)
;

ALTER TABLE Huesped ADD CONSTRAINT PK_Huesped
	PRIMARY KEY (k_tipoDocumento,k_numeroDocumento)
;

ALTER TABLE Huesped ADD CONSTRAINT CK_o_telefono CHECK (o_telefono > 0)
;

ALTER TABLE Huesped ADD CONSTRAINT CK_k_tipoDocumento CHECK (k_tipoDocumento IN ('CC','TI','TE','CE','NIT'))
;

ALTER TABLE Huesped ADD CONSTRAINT CK_k_numeroDocumento CHECK (k_numeroDocumento > 0)
;

ALTER TABLE Pago ADD CONSTRAINT PK_Pago
	PRIMARY KEY (k_pago)
;

ALTER TABLE Pago ADD CONSTRAINT CK_k_pago CHECK (k_pago > 0)
;

ALTER TABLE Pago ADD CONSTRAINT CK_v_totalpagado CHECK (v_totalPagado > 0)
;

ALTER TABLE Pago ADD CONSTRAINT CK_k_numeroCuenta CHECK (k_numeroCuenta > 0)
;

ALTER TABLE Persona ADD CONSTRAINT PK_Persona
	PRIMARY KEY (k_tipoDocumento,k_numeroDocumento)
;

ALTER TABLE Persona ADD CONSTRAINT CK_k_tipoDocumento CHECK (k_tipoDocumento IN ('CC','TI','TE','CE','NIT'))
;

ALTER TABLE Persona ADD CONSTRAINT CK_k_numeroDocumento CHECK (k_numeroDocumento > 0)
;

ALTER TABLE ProductoServicio ADD CONSTRAINT PK_ProductoServicio
	PRIMARY KEY (k_producto)
;

ALTER TABLE ProductoServicio ADD CONSTRAINT CK_k_producto CHECK (k_producto > 0)
;

ALTER TABLE ProductoServicio ADD CONSTRAINT CK_v_precioUnitario CHECK (v_precioUnitario > 0)
;

ALTER TABLE ProductoServicio ADD CONSTRAINT CK_i_tipo CHECK (i_tipo in ('P','S'))
;

ALTER TABLE Registro ADD CONSTRAINT PK_Registro
	PRIMARY KEY (k_numeroRegistro)
;

ALTER TABLE Registro ADD CONSTRAINT CK_k_reserva CHECK (k_reserva > 0)
;

ALTER TABLE Registro ADD CONSTRAINT CK_k_numeroRegistro CHECK (k_numeroRegistro > 0)
;

ALTER TABLE Registro ADD CONSTRAINT CK_k_numeroDocumento CHECK (k_numeroDocumento > 0)
;

ALTER TABLE Registro ADD CONSTRAINT CK_k_tipoDocumento CHECK (k_tipoDocumento IN ('CC','TI','TE','CE','NIT'))
;

ALTER TABLE Reserva ADD CONSTRAINT PK_Reserva
	PRIMARY KEY (k_reserva)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_i_estado CHECK (i_estado in ('pendiente','paga','cancelada'))
;

ALTER TABLE Reserva ADD CONSTRAINT CK_k_reserva CHECK (k_reserva > 0)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_q_nochesReservadas CHECK (q_nochesReservadas > 0)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_q_numeroPesonas CHECK (q_numeroPersonas > 0)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_v_precioEstadia CHECK (v_precioEstadia > 0)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_k_numeroHabitacion CHECK (k_numeroHabitacion > 0)
;

ALTER TABLE Reserva ADD CONSTRAINT CK_k_tipoDocumento CHECK (k_tipoDocumento IN ('CC','TI','TE','CE','NIT'))
;

ALTER TABLE Reserva ADD CONSTRAINT CK_numeroDocumento CHECK (k_numeroDocumento > 0)
;

ALTER TABLE Tipo ADD CONSTRAINT PK_Tipo
	PRIMARY KEY (k_tipo)
;

ALTER TABLE Tipo ADD CONSTRAINT CK_k_tipo CHECK (k_tipo in ('S','D','T'))
;

ALTER TABLE Tipo ADD CONSTRAINT CK_v_precioNoche CHECK (v_precioNoche > 0)
;

/* Create Foreign Key Constraints */

ALTER TABLE Cuenta ADD CONSTRAINT FK_Cuenta_Reserva
	FOREIGN KEY (k_reserva) REFERENCES Reserva (k_reserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Cuenta_ProductoServicio ADD CONSTRAINT FK_Cuenta_ProductoServicio_Cuenta
	FOREIGN KEY (k_numeroCuenta) REFERENCES Cuenta (k_numeroCuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Cuenta_ProductoServicio ADD CONSTRAINT FK_Cuenta_ProductoServicio_ProductoServicio
	FOREIGN KEY (k_producto) REFERENCES ProductoServicio (k_producto) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Habitacion ADD CONSTRAINT FK_Habitacion_Hotel
	FOREIGN KEY (k_hotel) REFERENCES Hotel (k_hotel) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Habitacion ADD CONSTRAINT FK_Habitacion_Tipo
	FOREIGN KEY (k_tipo) REFERENCES Tipo (k_tipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pago ADD CONSTRAINT FK_Pago_Cuenta
	FOREIGN KEY (k_numeroCuenta) REFERENCES Cuenta (k_numeroCuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Registro ADD CONSTRAINT FK_Registro_Huesped
	FOREIGN KEY (k_tipoDocumento,k_numeroDocumento) REFERENCES Huesped (k_tipoDocumento,k_numeroDocumento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Registro ADD CONSTRAINT FK_Registro_Reserva
	FOREIGN KEY (k_reserva) REFERENCES Reserva (k_reserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reserva ADD CONSTRAINT FK_Reserva_Habitacion
	FOREIGN KEY (k_numeroHabitacion) REFERENCES Habitacion (k_numeroHabitacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reserva ADD CONSTRAINT FK_Reserva_Persona
	FOREIGN KEY (k_tipoDocumento,k_numeroDocumento) REFERENCES Persona (k_tipoDocumento,k_numeroDocumento) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Cuenta
	IS 'Esta tabla guarda valores asociados al consumo del huesped dentro del hotel'
;

COMMENT ON COLUMN Cuenta.k_numeroCuenta
	IS 'Es el numero con el que se identifica cada cuenta'
;

COMMENT ON COLUMN Cuenta.i_estado
	IS 'Este permite saber si el valor del consumo asociado a la cuenta está pago o no'
;

COMMENT ON COLUMN Cuenta.v_valorConsumo
	IS 'Este es la suma de todos los productos o servicios que se consumieron en el hotel '
;

COMMENT ON COLUMN Cuenta.k_reserva
	IS 'Es el numero que identifica cada reserva'
;

 

 

COMMENT ON TABLE Cuenta_ProductoServicio
	IS 'Esta tabla es la asociacion de la cuenta y lo consumido en el hotel'
;

COMMENT ON COLUMN Cuenta_ProductoServicio.q_cantidad
	IS 'esta es el numero de veces que uso o consumio un servicio o un producto'
;

COMMENT ON COLUMN Cuenta_ProductoServicio.f_consumo
	IS 'Es la fecha donde el huesped hizp el consumo'
;

COMMENT ON COLUMN Cuenta_ProductoServicio.k_numeroCuenta
	IS 'Es el numero con el que se identifica cada cuenta'
;

COMMENT ON COLUMN Cuenta_ProductoServicio.k_producto
	IS 'Es el numero con el que se identifica cada producto '
;

 

COMMENT ON TABLE Habitacion
	IS 'Esta tabla contiene el numero de único que identifica cada habitación'
;

COMMENT ON COLUMN Habitacion.k_numeroHabitacion
	IS 'Este es el numero para identificar cada una de las habitaciones'
;

COMMENT ON COLUMN Habitacion.k_tipo
	IS 'Es el tipo de habitacion que se puede elegir (Simple, Doble, Triple)'
;

COMMENT ON COLUMN Habitacion.k_hotel
	IS 'Es el identificador del hotel'
;

COMMENT ON TABLE Hotel
	IS 'Esta tabla contiene los descuentos a la reserva y el aforo perimitido en el hotel '
;

COMMENT ON COLUMN Hotel.k_hotel
	IS 'Es el identificador del hotel'
;

COMMENT ON COLUMN Hotel.q_diasDescuento
	IS 'Es el numero de dias que se establece para aplicar por el descuento'
;

COMMENT ON COLUMN Hotel.t_descuento
	IS 'Es la tasa de descuento que aplica luego de hospedarse esos n dias '
;

COMMENT ON COLUMN Hotel.t_aforo
	IS 'Es el numero maximo de personas que pueden estar dentro del hotel'
;

COMMENT ON COLUMN Hotel.q_capacidad
	IS 'Capacidad máxima del hotel'
;

COMMENT ON TABLE Huesped
	IS 'Esta tabla colecciona los dato de la persona cuando ya es un huesped'
;

COMMENT ON COLUMN Huesped.o_direccion
	IS 'Esta es la direccion de residencia del huesped'
;

COMMENT ON COLUMN Huesped.o_telefono
	IS 'Este es el numero telefonico personal del huesped'
;

COMMENT ON COLUMN Huesped.f_nacimiento
	IS 'Fecha de nacimiento del huesped'
;

COMMENT ON COLUMN Huesped.k_tipoDocumento
	IS 'Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"'
;

COMMENT ON COLUMN Huesped.k_numeroDocumento
	IS 'Este el el numero de identificacion unico de la persona'
;

COMMENT ON TABLE Pago
	IS 'Esta tabla guarda toda la informacion relacionada al pago '
;

COMMENT ON COLUMN Pago.k_pago
	IS 'Este es el numero unico asociado a cada pago'
;

COMMENT ON COLUMN Pago.f_pago
	IS 'Fecha en la que se hizo el pago'
;

COMMENT ON COLUMN Pago.n_formapago
	IS 'Es la forma que elige el huesped para hacer el pago'
;

COMMENT ON COLUMN Pago.v_totalPagado
	IS 'Es el total a pagar'
;

COMMENT ON COLUMN Pago.k_numeroCuenta
	IS 'Es el numero con el que se identifica cada cuenta'
;

 

COMMENT ON TABLE Persona
	IS 'Esta tabla guarda los datos de la persona que hace una reserva pero aun no huesped'
;

COMMENT ON COLUMN Persona.k_tipoDocumento
	IS 'Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"'
;

COMMENT ON COLUMN Persona.k_numeroDocumento
	IS 'Este el el numero de identificacion unico de la persona'
;

COMMENT ON COLUMN Persona.n_primerNombre
	IS 'El primer nombre de la persona'
;

COMMENT ON COLUMN Persona.n_segundoNombre
	IS 'El segundo nombre de la persona (Opcional)'
;

COMMENT ON COLUMN Persona.n_primerApellido
	IS 'primer apellido de la persona'
;

COMMENT ON COLUMN Persona.n_segundoApellido
	IS 'segundo apellido de la persona (opcional)'
;

COMMENT ON COLUMN ProductoServicio.k_producto
	IS 'Es el numero con el que se identifica cada producto '
;

COMMENT ON COLUMN ProductoServicio.n_producto
	IS 'Es el nombre de cada producto'
;

COMMENT ON COLUMN ProductoServicio.v_precioUnitario
	IS 'El valor por unidad de cada producto'
;

COMMENT ON COLUMN ProductoServicio.i_tipo
	IS 'Permite saber si es un producto o un servicio lo que consumió el huésped'
;

COMMENT ON TABLE Registro
	IS 'Esta tabla guarda los datos de la entrada y salida del hotel'
;

COMMENT ON COLUMN Registro.k_numeroRegistro
	IS 'Es el numero para identificar cada registro'
;

COMMENT ON COLUMN Registro.f_entrada
	IS 'Fecha del check-in en el hotel'
;

COMMENT ON COLUMN Registro.f_salida
	IS 'fecha del check-out del hotel'
;

COMMENT ON COLUMN Registro.k_tipoDocumento
	IS 'Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"'
;

COMMENT ON COLUMN Registro.k_numeroDocumento
	IS 'Este el el numero de identificacion unico de la persona'
;

COMMENT ON COLUMN Registro.k_reserva
	IS 'Es el numero que identifica cada reserva'
;

 

 

COMMENT ON TABLE Reserva
	IS 'En esta tabla se almacena toda la información relacionada a la reserva (dias, fechas, numero de personas, precio y el estado de esta).'
;

COMMENT ON COLUMN Reserva.k_reserva
	IS 'Es el numero que identifica cada reserva'
;

COMMENT ON COLUMN Reserva.f_inicio
	IS 'Es la fecha desde que la persona estaria hospedada en el hotel'
;

COMMENT ON COLUMN Reserva.f_fin
	IS 'Es la fecha en la que terminaria la reserva en el hotel'
;

COMMENT ON COLUMN Reserva.f_reserva
	IS 'Es la fecha exacta en la que se hace la reserva'
;

COMMENT ON COLUMN Reserva.q_nochesReservadas
	IS 'Es el numero de noches que la persona reserva'
;

COMMENT ON COLUMN Reserva.q_numeroPersonas
	IS 'Es el numero de personas que estarian incluidas dentro de la reserva'
;

COMMENT ON COLUMN Reserva.v_precioEstadia
	IS 'Es el precio total de la estadia en el hotel'
;

COMMENT ON COLUMN Reserva.i_estado
	IS 'Este atributo permite conocer si la reserva ya esta paga, no paga o cancelada'
;

COMMENT ON COLUMN Reserva.k_numeroHabitacion
	IS 'Este es el numero para identificar cada una de las habitaciones'
;

COMMENT ON COLUMN Reserva.k_tipoDocumento
	IS 'Este atributo permite identificar si tiene "CC","TI","TE","CE" o "NIT"'
;

COMMENT ON COLUMN Reserva.k_numeroDocumento
	IS 'Este el el numero de identificacion unico de la persona'
;

 

COMMENT ON TABLE Tipo
	IS 'Esta tabla contiene el precio de cada noche, dependiendo el tipo de habitacion que se haya elegido'
;

COMMENT ON COLUMN Tipo.k_tipo
	IS 'Es el tipo de habitacion que se puede elegir (Simple, Doble, Triple)'
;

COMMENT ON COLUMN Tipo.v_precioNoche
	IS 'Es el valor que se le da por noche a cada habitacion, dependiendo el tipo que elija'
;
